### ISSUE TITLE
Checklist posten

### ISSUE THREAD

**Issue by DaanCarst** [WesleySchorel/Toolgankelijk-Sprint-18#12]
- [x] Checkbox kunnen POSTEN naar hygraph
- [x] Dynamisch aan- en uitvinken van de checkboxen
- [ ] Totaal waarden gevinkte checkboxen doorgeven naar websites
